services:
  app:
    image: restfulgym:latest
    ports:
      - "8080:8080"
    environment:
      - DB_URL=db:5432/postgres
      - DB_USER=admin
      - DB_PASSWORD=root
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    ports:
      - "5432"
