spring:
  application:
    name: RestfulGym
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost:5432/postgres}
    username: admin
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: true
  sql:
    init:
      mode: always
logging:
  level:
    org.springframework.security: trace
jwt:
  secret: sdfhsakldfhjsakdfhjaskdfhjaskdjfhaskfhaskdfhjaksdhskahfkjadsakaskfjdaslkjfalskdfjaslkdjflk
  lifetime: 30m